# Generated by Django 3.2.4 on 2021-09-13 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fut',
            name='fecha',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
