# Generated by Django 3.2.4 on 2021-08-31 04:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramitesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='alumno',
            field=models.ForeignKey(default=datetime.date(2021, 8, 30), on_delete=django.db.models.deletion.CASCADE, to='tramitesApp.alumno'),
            preserve_default=False,
        ),
    ]
