# Generated by Django 3.2.4 on 2021-09-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramitesApp', '0002_auto_20210903_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiporequisito',
            name='requisitos',
        ),
        migrations.RemoveField(
            model_name='tipotramite',
            name='tipoRequisitos',
        ),
        migrations.AddField(
            model_name='requisito',
            name='tipoRequisitos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tramitesApp.tiporequisito'),
        ),
        migrations.AddField(
            model_name='tiporequisito',
            name='tipoTramites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tramitesApp.tipotramite'),
        ),
    ]
