# Generated by Django 3.2.4 on 2021-08-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramitesApp', '0002_tramite_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='alumno',
        ),
    ]
