# Generated by Django 3.2.4 on 2021-09-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramitesApp', '0004_auto_20210904_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('alumnos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tramitesApp.alumno')),
                ('tipoTramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramitesApp.tipotramite')),
            ],
        ),
    ]
