# Generated by Django 3.2.4 on 2021-09-07 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitesApp', '0005_fut'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fechatram',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
