# Generated by Django 3.2.4 on 2021-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitesApp', '0006_tramite_fechatram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandejatramite',
            name='fecha',
        ),
        migrations.AddField(
            model_name='bandejatramite',
            name='fechabandeja',
            field=models.DateField(null=True),
        ),
    ]
