# Generated by Django 3.2.4 on 2021-09-10 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitesApp', '0007_auto_20210907_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisito',
            name='archivo',
        ),
        migrations.AddField(
            model_name='tramite',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='requisito'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='fechatram',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
