# Generated by Django 3.2.4 on 2021-09-12 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramitesApp', '0009_alter_tramite_fechatram'),
    ]

    operations = [
        migrations.AddField(
            model_name='fut',
            name='objeto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fut',
            name='estado',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='archivo',
            field=models.FileField(null=True, upload_to='requisito'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='fechatram',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
